### ISSUE TITLE
Option to show both words at the same time?

### ISSUE THREAD

**Issue by Dres49** [thekampany/MMM-learnlanguage#1]
Dear thekampany,

thanks for the idea and writing the MMM-learnmodule.
It would be great if one can see both words at the same time - because sometimes one stands only a short time in front of the screen. Is there an option to switch on a "show both words"-modus?

Thanks and best regards
Dres49.

**Comment by thekampany** [comment]
Yes, great idea. Will work on that one when i have sone time

**Comment by thekampany** [comment]
Option added
