### ISSUE TITLE
Characters with accents do not show properly

### ISSUE THREAD

**Issue by RaspNewby** [thekampany/MMM-learnlanguage#2]
Great module! I tried to use the module to learn Spanish. However, the characters with accents do not show properly. Instead I see a question mark. I guess this could also be due to settings on my pi. Are your characters with accents displaying properly?

**Comment by thekampany** [comment]
Hmm. Not displaying correct indeed.

**Comment by RaspNewby** [comment]
Found it. Encoding of the csv is ascii or iso-.... The pi reads UTF-8 as standard. Once the csv file is converted into UTF-8, everything works fine.

**Comment by Dubidubiduu** [comment]
Why is this closed, it's still a bug and it's still ocurring.

**Comment by thekampany** [comment]
uploaded the csv files with utf8 encoding.
