### ISSUE TITLE
Oscillating/flashing words

### ISSUE THREAD

**Issue by Dubidubiduu** [thekampany/MMM-learnlanguage#4]
From time to time, the word-pairs are flashing/switching. Seeing a wordpair for a milisecond or so, then the other one again.

My setting:
116   {
117   module: "MMM-learnlanguage",
118   position: "top_left",
119   config: {
120     language: "spanish",
121     nextWordInterval: 90000,
122     showpair: "showboth"
123     }
124 },

**Comment by sandman12345678** [comment]
can confirm have the same error. Somehow it worked before. Not really sure whats the matter now.
Copyed the config directly without making any changes.

edit_ It seems the error only occurs if you acess your mirror over RDP. If I connect the Raspy directoy via HDMI the error disapers.

Cheers

**Comment by KristjanESPERANTO** [comment]
The current logic makes a constant update of the HTML (even if the content has not changed). With PR #7, the HTML will be only updated when the content changes.
